-- User Management Tables updated in version 2025.1.0
    
drop view if exists USER_RIGHTS;

create table if not exists SUBPROFILES (
    PRP_ID integer generated by default as identity primary key,
    PRP_PARENT integer,
    PRP_CHILD integer,
    constraint PRP_PARENT_CHILD_UC unique (PRP_PARENT, PRP_CHILD),
    constraint PRP_CHILD_FK foreign key (PRP_CHILD) references PROFILES (PRF_ID) on delete cascade,
    constraint PRP_PARENT_FK foreign key (PRP_PARENT) references PROFILES (PRF_ID) on delete cascade);

insert into USER_TITLES (UST_DELETED) values (0);
