-- Connection management stored into the database..
--

create table LOCALAUTH (
    LAU_ID integer generated by default as identity primary key,
    LAU_LOGIN varchar(255), 
    LAU_PASSWORD varchar(255), 
    LAU_USER integer,
    LAU_LOCKED integer default 0,
    LAU_PWDUPDATE timestamp default current_timestamp,
    LAU_UPDATE timestamp default current_timestamp);

alter table LOCALAUTH add constraint LAU_USER_FK foreign key (LAU_USER) references USERS (USR_ID) on delete cascade;

-- initialization of the first Admin user.
insert into LOCALAUTH (LAU_LOGIN, LAU_PASSWORD, LAU_USER) values ('admin', 'quadra', 1);

create index LAU_USER_INDEX on LOCALAUTH (LAU_USER);
create index LAU_LOGIN_INDEX on LOCALAUTH (LAU_LOGIN);
