# .github/release.yml

changelog:
  sections:
    - title: Enhancements
      labels: ["enhancement"]
    - title: Bugs
      labels: ["bug"]
    - title: Security Vulnerabilities
      labels: ["vulnerability"]
