-- ARCAD Foundation Service Database Versioning table
--

create table ARCADDBV (
    DBV_ID integer generated by default as identity primary key,
    DBV_CODE varchar(50),
    DBV_VERSION integer,
    DBV_LABEL varchar(255),
    DBV_UPDATE timestamp default current_timestamp);
