package com.arcadsoftware.rest;

/**
 * This interface implement a generic operator used to generate Server Sent Events unique identifier.
 * 
 * <p>
 * Implementation must be multi-threaded counter generators and implement the Cloneable interface.
 * 
 * <p>
 * The 
 * @author ARCAD Software
 * @see SSERepresentation
 * @see Cloneable
 */
public interface ISSEIdGenerator extends Cloneable {

	/**
	 * Get the current ID value and "increment it to the next one.
	 * 
	 * @return a non null value, different for each call.
	 */
	public String getAndIncrement();
	
	/**
	 * Reset the current value of this 
	 * 
	 * @param id a non null value.
	 */
	public void reset(String id);
	
	/**
	 * Return true if and only if the given "id" is an older value generated by this counter generator.
	 * @param id
	 * @return
	 */
	public boolean possess(String id);
	
	public SSELongIdGenerator clone();
}
