/*******************************************************************************
 * Copyright (c) 2024 ARCAD Software.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     ARCAD Software - initial API and implementation
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. HTMLParserConstants.java */
package com.arcadsoftware.email.internal;

public interface HTMLParserConstants {

  int EOF = 0;
  int TagName = 1;
  int DeclName = 2;
  int Comment1 = 3;
  int Comment2 = 4;
  int Word = 5;
  int LET = 6;
  int NUM = 7;
  int Entity = 8;
  int Space = 9;
  int SP = 10;
  int Punct = 11;
  int ArgName = 12;
  int ArgEquals = 13;
  int TagEnd = 14;
  int ArgValue = 15;
  int ArgQuote1 = 16;
  int ArgQuote2 = 17;
  int Quote1Text = 19;
  int CloseQuote1 = 20;
  int Quote2Text = 21;
  int CloseQuote2 = 22;
  int CommentText1 = 23;
  int CommentEnd1 = 24;
  int CommentText2 = 25;
  int CommentEnd2 = 26;

  int DEFAULT = 0;
  int WithinTag = 1;
  int AfterEquals = 2;
  int WithinQuote1 = 3;
  int WithinQuote2 = 4;
  int WithinComment1 = 5;
  int WithinComment2 = 6;



}
