-- SSH Connections table
--

CREATE TABLE IF NOT EXISTS SSH_KEYS (
    SHK_ID integer generated by default as identity primary key,
    SHK_COMMENT varchar(500),
    SHK_FINGERPRINT varchar(70),
    SHK_NAME varchar(1000),
    SHK_TYPE varchar(10),
    SHK_PASSPHRASE varchar(5000),
    SHK_LENGTH integer,
    SHK_UPDATE timestamp default current_timestamp);
