-- LDAP connection management.
--

create table LDAPAUTH (
    LDA_ID integer generated by default as identity primary key,
    LDA_LOGIN varchar(255), 
    LDA_USER integer,
    LDA_UPDATE timestamp default current_timestamp);

alter table LDAPAUTH add constraint LDA_USER_FK foreign key (LDA_USER) references USERS (USR_ID) on delete cascade;

create index LDA_USER_INDEX on LDAPAUTH (LDA_USER);
create index LDA_LOGIN_INDEX on LDAPAUTH (LDA_LOGIN);

-- End of LDAP connection management.
-- 