openapi: 3.1.0 #Documentation Fragment
# This description is the fisrt static element which is always included into documentation.
# It contain some reusable components which are managed through the Restlet framework for the whole API.
components:
  schemas:
    ErrorMessage:
      xml:
        name: 'message'
      type: object
      description: Ce document décrit un message d'erreur HTTP.'
      properties:
        name:
          type: string
          description: Le message d'erreur.
          xml:
            attribute: true
        code:
          type: integer
          description: Le code HTTP de l'erreur.
          xml:
            attribute: true
        href:
          type: string
          format: uri
          description: L'URL de la documentation de cette erreur HTTP.
          xml:
            attribute: true
        description:
          type: string
          description: Une description lisible par un être humain de la cause de l'erreur (Notez que dans un document XML la description est la valeur contenue dans le tag "message".)
    About:
      type: object
      properties:
        about:
          type: object
          properties:
            application:
              type: object
              description: Regroupe un ensemble d'information relatives à cette application.
              properties:
                name:
                  type: string
                  description: Le nom de cette application.
                version:
                  type: string
                  description: La version courante de cette application.
                author:
                  type: string
                  description: Le propriétaire légal de cette application.
                owner:
                  type: string
                  description: Le propriétaire actuel de l'application, relativement à la licence d'utilisation.
                contact:
                  type: string
                  format: email
                  description: Une adresse email de contact relative à l'administration de cette application. 
                license:
                  type: string
                  description: La licence d'utilisation relative à cette application.
                licenseurl:
                  type: string
                  format: uri
                  description: L'URL d'un site web exposant le texte de la licence d'utilisation de cette application.
                usage:
                  type: string
                  description: Une note de copyright.
                url:
                  type: string
                  format: uri
                  description: L'URL d'un site web contenant la documentation relative à l'usage de cette application.
                  xml:
                    name: 'lisenceUrl'
                sysparam:
                  type: string
                  description: Les paramètres systèmes permettant de générer une clé de licence pour cette installation.
            framework:
              type: object
              description: Ensemble d'information techniques sur cette installation. 
              properties:
                vendor:
                  type: string
                  description: Nom de l'implementation du framework hébergeant cette API REST.
                version:
                  type: string
                  description: Version courante de l'implémentation du framework.
                webstart:
                  type: string
                  format: date
                  description: Date de démarrage de cette API REST.
                start:
                  type: string
                  format: date
                  description: Date de démarrage du serveur d'application.
  responses:
    NotFound:
      description: La resource spécifiée n'a pas été trouvée, ou n'est pas en état de fonctionner.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xhtml+xml:
          schema:
            type: string
        text/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        text/html:
          schema:
            type: string
    UnexpectedError:
      description: Une erreur inatendue c'est produite, elle peut être due à un problème de stockage (lié à la base de données) ou une malfonction du programme. Le message lié à l'erreur détaillera la cause exacte du problème.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xhtml+xml:
          schema:
            type: string
        text/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        text/html:
          schema:
            type: string
    Unauthorized:
      description: L'authentification de l'utilisateur a échoué sur cette ressource. Due à un mauvais login ou mot de passe, ou la connection est verrouillée.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xhtml+xml:
          schema:
            type: string
        text/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        text/html:
          schema:
            type: string
    Unsupported:
      description: Le mediatype utilisé dans le corps de la requête n'est pas supporté.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xhtml+xml:
          schema:
            type: string
        text/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        text/html:
          schema:
            type: string
    Forbidden:
      description: L'utilisateur authentifié ne possède pas les droits nécessaire pour réaliser cette opération.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        application/xhtml+xml:
          schema:
            type: string
        text/xml:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
        text/html:
          schema:
            type: string
paths:
  /about:
    description: Ce service fourni des informations sur l'API REST, incluant son numéro de version et la date du dernier démarrage.
    get:
      summary: Information au sujet de l'API REST. 
      description: Renvois les informations générales sur cette API REST. Si cette ressource renvois une erreur 404 alors le serveur ne sera pas en état de répondre à tout autre requête. 
      tags:
      - Framework
      responses:
        "200":
          description: Les informations au sujet de cette API REST. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/About'
            application/xml:
              schema:
                $ref: '#/components/schemas/About'
            application/xhtml+xml:
              schema:
                type: string
            text/xml:
              schema:
                $ref: '#/components/schemas/About'
            text/html:
              schema:
                type: string
            text/plain:
              schema:
                type: string
        "404":
          $ref: '#/components/responses/NotFound' 
        "500":
          $ref: '#/components/responses/UnexpectedError' 
        default:
          description: Une erreur inatentu est survenue.