# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Manual Release Notes

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Generate RN for tag (/!\ will override current RN)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
       
    - name: Set up JDK 17 and 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
         
    - run: npm install @cjbarth/github-release-notes -g
      shell: bash
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y jq
      shell: bash
    - name: Generate release notes with gren
      run: gren release --data-source=issues -B -t ${{ inputs.tags }} -o -g label
      env:
        GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash

    - name: Delete tag
      shell: bash
      run: git push --delete origin :refs/tags/${{ github.ref_name }}
